INSERT INTO infobox_configuration VALUES ('#tID#', '', 'categories.php', 'BOX_HEADING_CATEGORIES', 'yes', 'left', 1, 'now()', 'now()', 'browse by categories:', 'infobox', '#2B2B2B');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'theme_select.php', 'BOX_HEADING_TEMPLATE_SELECT', 'no', 'left', 6, 'now()', 'now()', 'Select Template', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'reviews.php', 'BOX_HEADING_REVIEWS', 'no', 'right', 5, 'now()', 'now()', 'Product Reviews', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'specials.php', 'BOX_HEADING_SPECIALS', 'no', 'left', 2, 'now()', 'now()', 'Specials', 'infobox', '#FFFFFF');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'search.php', 'BOX_HEADING_SEARCH', 'no', 'left', 1, 'now()', 'now()', 'Quick Find', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'manufacturers.php', 'BOX_HEADING_MANUFACTURERS', 'yes', 'left', 2, 'now()', 'now()', 'Manufacturers:', 'infobox', '#2B2B2B');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'manufacturer_info.php', 'BOX_HEADING_MANUFACTURER_INFO', 'no', 'left', 15, 'now()', 'now()', 'Manufacturers Info', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'product_notifications.php', 'BOX_HEADING_NOTIFICATIONS', 'no', 'left', 16, 'now()', 'now()', 'Notifications', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'tell_a_friend.php', 'BOX_HEADING_TELL_A_FRIEND', 'no', 'left', 17, 'now()', 'now()', 'Tell A Friend', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'whats_new.php', 'BOX_HEADING_WHATS_NEW', 'no', 'right', 2, 'now()', 'now()', 'Latest product', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'shop_by_price.php', 'BOX_HEADING_SHOP_BY_PRICE', 'no', 'left', 19, 'now()', 'now()', 'Shop by Price', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'featured.php', 'BOX_HEADING_FEATURED', 'no', 'left', 20, 'now()', 'now()', 'Featured', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'affiliate.php', 'BOX_HEADING_AFFILIATE', 'no', 'left', 21, 'now()', 'now()', 'Affiliate Info', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'links.php', 'BOX_HEADING_LINKS', 'no', 'left', 3, 'now()', 'now()', 'Links', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'whos_online.php', 'BOX_HEADING_WHOS_ONLINE', 'no', 'left', 22, 'now()', 'now()', 'Who\'s Online', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'googlead.php', 'BOX_GOOGLE_AD_BANNER_HEADING', 'no', 'left', 23, 'now()', 'now()', 'Google Ad', 'infobox', '#000000');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'shopping_cart.php', 'BOX_HEADING_SHOPPING_CART', 'no', 'right', 0, 'now()', 'now()', 'Shopping Cart', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'customer_gv.php', 'BOX_HEADING_GIFT_VOUCHER', 'no', 'right', 2, 'now()', 'now()', 'Gift Voucher', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'loginbox.php', 'BOX_HEADING_LOGIN', 'no', 'right', 3, 'now()', 'now()', 'Your Account', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'best_sellers.php', 'BOX_HEADING_BESTSELLERS', 'no', 'right', 3, 'now()', 'now()', 'Best Sellers', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'order_history.php', 'BOX_HEADING_CUSTOMER_ORDERS', 'no', 'right', 5, 'now()', 'now()', 'Order History', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'languages.php', 'BOX_HEADING_LANGUAGES', 'no', 'left', 6, 'now()', 'now()', 'Languages', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'currencies.php', 'BOX_HEADING_CURRENCIES', 'yes', 'left', 3, 'now()', 'now()', 'Currencies', 'infobox', '#2B2B2B');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'downloads.php', 'BOX_HEADING_DOWNLOADS', 'no', 'right', 10, 'now()', 'now()', 'You Have a Download', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'donate.php', 'BOX_HEADING_DONATE', 'no', 'right', 11, 'now()', 'now()', 'Donate', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'wishlist.php', 'BOX_HEADING_WISHLIST', 'no', 'right', 14, 'now()', 'now()', 'Wishlist', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'boxad.php', 'BOX_AD_BANNER_HEADING', 'no', 'right', 15, 'now()', 'now()', 'Advertise', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'faq.php', 'BOX_HEADING_FAQ', 'yes', 'right', 1, 'now()', 'now()', 'FaqDesk Latest', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'articles.php', 'BOX_HEADING_ARTICLES', 'no', 'right', 2, 'now()', 'now()', 'Latest News', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'information_table.php', 'BOX_HEADING_INFORMATION_TABLE', 'no', 'right', 1, 'now()', 'now()', 'Store Information', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'baner.php', 'BOX_HEADING_BANNER', 'yes', 'right', 2, 'now()', 'now()', 'Store Information', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'baner1.php', 'BOX_HEADING_BANNER1', 'yes', 'right', 3, 'now()', 'now()', 'Store Information', 'infobox', '#ffffff');
INSERT INTO infobox_configuration VALUES ('#tID#', '', 'baner2.php', 'BOX_HEADING_BANNER2', 'yes', 'right', 4, 'now()', 'now()', 'Store Information', 'infobox', '#ffffff');
UPDATE `configuration` SET `configuration_value` = '2'WHERE `configuration_id` = 215 LIMIT 1 ;
UPDATE `configuration` SET `configuration_value` = 'column' WHERE `configuration_id` =89 LIMIT 1;
UPDATE `configuration` SET `configuration_value` = '4' WHERE `configuration_id` =169 LIMIT 1;
UPDATE template SET date_added= now(), last_modified= now(), template_image= "preview.jpg", template_cellpadding_main ="0", template_cellpadding_sub= "0", template_cellpadding_left= "0", template_cellpadding_right= "0", site_width= "780", include_column_left= "yes", include_column_right= "yes", box_width_left= "180",box_width_right= "180", main_table_border= "yes", active= "1", show_heading_title_original="no",languages_in_header= "no", cart_in_header= "no",show_header_link_buttons="no", module_one= "", module_two= "featured.php", module_three= "", module_four= "", module_five= "", module_six= "", customer_greeting= "no", side_box_left_width= "0", side_box_right_width= "0" WHERE template_id="#tID#"